### ISSUE TITLE
A few problems using Akatab for the Shifinagh of the Tawallammat (ttq) language

### ISSUE THREAD

**Issue by GreatCharter** [silnrsi/font-akatab#1]
Akatab is a beautiful font and welcome addition to the very limited choices in Shifinagh fonts.  I have been using the Tagmukay font for some time and recently found out about the Akatab font.  The description of the Akatab font says it is useful not only for Tamahaq but other Tamashek languages as well.  Tawallammat is one of the Tamashek languages.  However, I encountered several problems in my initial attempt to use the Akatab font.  There may be more problems with using Akatab for Tawallammat, but I thought before going deeper I'd check to see if changes to address the intial problems are feasible.  If so I'd be glad to explore futher, if not I'll just keep using Tagmukay.

Some specific problems I encountered using the Akatab font for Tawallammat (ttq) Shifinagh are as follows:

1. Many of the biconsonant glyphs don't correspond to the traditional biconsonants of Tawallammat.
2. Most importantly, some of consonant combination rules and corresponding glyphs needed for Tawallammat Shifinagh are missing, including (but not limited to) the rules for: enza, enda, enja, engha
3. A minor problem involves the final "a" (single dot) after a "w" (double dot). In Shifinagh "wa" can look very much like "k", because both involve three dots similarly arranged. In traditional Tawallammat Shifinagh confusion is avoided by separating out the final "a" dot futher to the right than the third dot in the "k", and/or by elongating the "a" dot horizontally, so that it becomes more like a short dash.

**Comment by jcoblentz** [comment]
Tawallammat glyphs added in v 3.000
